name: Unit Tests
on:
  workflow_dispatch: null
  pull_request:
    types: [ready_for_review]
jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Update system packages
        run: sudo apt-get update -y

      - name: Install system deps
        run: sudo apt-get install -y build-essential bats parallel netcat

      - name: Setup Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # pin@v2
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Test the CLI
        run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
